### ISSUE TITLE
It can not work after npm start

### ISSUE THREAD

**Issue by computing-bioX** [ElasticBottle/primer_checker#1]
I think you can push your work further to solve the problems, that is when you npm start the web such as "https://mendel3.bii.a-star.edu.sg/METHODS/corona/gamma/primer/build/", then it actually can not work for any primer data. And you will get an error which is "https://mendel3.bii.a-star.edu.sg/METHODS/corona/gamma/primer/build/error".  So can you fix it quickly?

**Comment by ElasticBottle** [comment]
Hi,

Thanks for opening an issue, I think the main problem is the fact that there is no backend in place when you just run Npm start right now. You need to have your own backend server running blast in order for this to work. Hope this helps!

**Comment by computing-bioX** [comment]
![error](https://user-images.githubusercontent.com/87118940/125736018-670d10a9-3ac9-43dc-b951-4ff271a25eba.jpg)
You can inspect the figure I attached. I do not know how to build a backend for your frontend, you'd better give a detailed user guide to instruct step by step.
